server:
  port: 8090

spring:
  application:
    name: accounts

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bankapp
    username: s
    password: sa

    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: create
        #ddl-auto: none

      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          # Ниже - адрес сервера авторизации для получения токена
          issuer-uri: http://localhost:8080/realms/master # Для запуска локально
          #issuer-uri: http://keycloak:8080/realms/master # Для запуска в Docker

  sql:
    init:
      mode: always