server:
  port: 8081

spring:
  application:
    name: front-ui

  cloud:
    consul:
      host: localhost           # Адрес Consul-агента (по умолчанию localhost)
      port: 8500
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        prefix: config           # Префикс в KV-хранилище Consul (по умолчанию "config")
        defaultContext: application  # Контекст по умолчанию
        import-check:
          enabled: false
      discovery:
        prefer-ip-address: true
        ip-address: localhost

  security:
    oauth2:
      client:
        provider:
          keycloak:
            # Ниже - адрес сервера авторизации для получения токена
            issuer-uri: http://localhost:8080/realms/master # Для запуска локально
            #issuer-uri: http://keycloak:8080/realms/master # Для запуска в Docker
        registration:
          front-ui: # Описание клиента OAuth2
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: front-ui
            client-secret: BZSkEMkx2BETc6WB6XXV5nHG2BfAcY48
            scope: profile
            clientAuthenticationMethod: client_secret_post # Способ передачи секрета

module-accounts: http://localhost:8090/